### ISSUE TITLE
Post processing moving failure after update

### ISSUE THREAD

**Issue by Obscurax** [barbequesauce/Watcher3#12]
** Commit: last
** Operating System: Server 2019
** Python Version [python -V]: python-3.7.3-amd64
** What happened: Post processing moving failure
Possibly related to this commit? https://github.com/barbequesauce/Watcher3/commit/9d64ac7cfc5ca815fdb5e12c88bb9d771f6132d4
** Logs:
```
INFO [2019-07-31 14:20:16,737] core.postprocessing.default.156: #################################
INFO [2019-07-31 14:20:16,737] core.postprocessing.default.157: Post-processing request received.
INFO [2019-07-31 14:20:16,737] core.postprocessing.default.158: #################################
INFO [2019-07-31 14:20:16,737] core.postprocessing.get_movie_file.236: Finding movie file.
INFO [2019-07-31 14:20:16,784] core.postprocessing.get_movie_file.262: Largest file in directory \\kratos\dump\Watcher\Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS is \b80fdf6c32cd47758891b0d29b5e8984.mkv, processing this file.
INFO [2019-07-31 14:20:16,784] core.postprocessing.default.186: Gathering release information.
INFO [2019-07-31 14:20:16,784] core.postprocessing.get_movie_info.284: Searching local database for guid.
INFO [2019-07-31 14:20:16,800] core.postprocessing.get_movie_info.287: Local release info found by guid.
INFO [2019-07-31 14:20:16,800] core.postprocessing.get_movie_info.317: Searching local database by imdbid.
INFO [2019-07-31 14:20:16,800] core.postprocessing.get_movie_info.320: Movie data found locally by imdbid.
INFO [2019-07-31 14:20:16,800] core.library.from_file.389: Gathering metadata for \\kratos\dump\Watcher\Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS\b80fdf6c32cd47758891b0d29b5e8984.mkv.
INFO [2019-07-31 14:20:16,800] core.library.parse_filename.513: Parsing directory name for movie information: Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS.
INFO [2019-07-31 14:20:16,800] core.library.parse_filename.521: Found {'year': 2019, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'group': 'SPARKS', 'title': 'Alita Battle Angel', 'release_name': 'Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS'} in filename.
INFO [2019-07-31 14:20:16,800] core.library.parse_media.459: Parsing codec data from file \\kratos\dump\Watcher\Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS\b80fdf6c32cd47758891b0d29b5e8984.mkv.
INFO [2019-07-31 14:20:16,815] core.postprocessing.default.194: Post-processing as Complete.
INFO [2019-07-31 14:20:16,815] core.postprocessing.complete.478: Marking guid as Finished.
INFO [2019-07-31 14:20:16,815] core.library.searchresults.928: Marking guid http://127.0.0.1:5076/nzbhydra2/getnzb/api/-1048928276332592101?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423 as Finished.
INFO [2019-07-31 14:20:16,815] core.library.searchresults.933: Marking http://127.0.0.1:5076/nzbhydra2/getnzb/api/-1048928276332592101?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423 as Finished in SEARCHRESULTS.
INFO [2019-07-31 14:20:16,831] core.library.searchresults.938: Successfully marked http://127.0.0.1:5076/nzbhydra2/getnzb/api/-1048928276332592101?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423 as Finished in SEARCHRESULTS.
INFO [2019-07-31 14:20:16,831] core.library.markedresults.981: Marking http://127.0.0.1:5076/nzbhydra2/getnzb/api/-1048928276332592101?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423 as Finished in MARKEDRESULTS.
INFO [2019-07-31 14:20:16,847] core.library.markedresults.986: Successfully marked http://127.0.0.1:5076/nzbhydra2/getnzb/api/-1048928276332592101?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423 as Finished in MARKEDRESULTS.
INFO [2019-07-31 14:20:16,847] core.postprocessing.complete.519: Setting MOVIE status.
INFO [2019-07-31 14:20:16,847] core.library.movie_status.1016: Determining appropriate status for movie tt0437086.
INFO [2019-07-31 14:20:16,847] core.library.movie_status.1053: Setting MOVIES tt0437086 status to Finished.
INFO [2019-07-31 14:20:16,862] core.library.convert_to_db.565: Converting movie metadata to database structure for Alita: Battle Angel.
INFO [2019-07-31 14:20:16,862] core.postprocessing.mover.778: ## Moving Downloaded Files
INFO [2019-07-31 14:20:17,003] core.postprocessing.mover.850: Moving \\kratos\dump\Watcher\Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS\b80fdf6c32cd47758891b0d29b5e8984.mkv to \\kratos\films\Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS\
ERROR [2019-07-31 14:20:17,034] core.postprocessing.mover.855: Mover failed: Could not move file.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 852, in mover
    shutil.copyfile(current_file_path, target_folder)
  File "C:\Python37\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: '\\\\kratos\\films\\Alita.Battle.Angel.2019.1080p.BluRay.x264-SPARKS\\'
INFO [2019-07-31 14:20:17,034] core.postprocessing.renamer.665: ## Renaming Downloaded Files
ERROR [2019-07-31 14:20:17,034] cherrypy.error.2207760838104.error.219: [31/Jul/2019:14:20:17] HTTP 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Program Files (x86)\Watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 196, in default
    response = self.complete(data)
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 548, in complete
    new_file_name = self.renamer(data)
  File "C:\Program Files (x86)\Watcher\core\postprocessing.py", line 677, in renamer
    path = os.path.split(data['finished_file'])[0]
  File "C:\Python37\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
INFO [2019-07-31 14:20:17,034] cherrypy.error.2207760838104.error.219: [31/Jul/2019:14:20:17] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  ACCEPT-ENCODING: identity
  HOST: 127.0.0.1:9090
  CONNECTION: close
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 282
INFO [2019-07-31 14:21:34,863] core.ajax.get_log_text.512: Dumping log file log.txt to text.
```

**Comment by barbequesauce** [comment]
Ouch. I see the issue, but need to research why it is happening. Sorry about that.

The change was made because shutil.move doesn’t properly move when traversing distinct filesystems; it gets the copy right but doesn’t reliably unlink the source after. Apparently shutil.copyfile doesn’t like Windows UNCs.

This might take some time, so you might want to roll back those two commits manually...

**Comment by Obscurax** [comment]
Thanks for the explanation. Although I don't know much about coding, this made sense. I've reverted those commits for now. If you'd like me to test something, hit me up.

**Comment by Obscurax** [comment]
Seems like this commit https://github.com/barbequesauce/Watcher3/commit/5b7fc67c734eacb4625a003da785a7bcd2ff9e49 fixed it.

**Comment by barbequesauce** [comment]
Thanks - it seemed like it was working on my side, wasn’t ready to declare victory without feedback :)
