### ISSUE TITLE
NZBGet prost processing

### ISSUE THREAD

**Issue by Obscurax** [barbequesauce/Watcher3#125]
Sometimes the post processing of a download fails. 
Post-process-script Watcher.py failed (terminated with unknown status). 

**Desktop (please complete the following information):**
 - OS: Server 2019
 - Python: python-3.7.6-amd64

`error	Thu Feb 06 2020 15:09:13	Post-process-script Watcher.py for A.Beautiful.Day.in.the.Neighborhood.2019.2160p.UHD.BluRay.x265-TERMiNAL failed (terminated with unknown status)
info	Thu Feb 06 2020 15:09:13	Watcher: socket.timeout: timed out
info	Thu Feb 06 2020 15:09:13	Watcher: data = self._sock.recv(self._rbufsize)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\socket.py", line 480, in readline
info	Thu Feb 06 2020 15:09:13	Watcher: line = self.fp.readline(_MAXLINE + 1)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\httplib.py", line 404, in _read_status
info	Thu Feb 06 2020 15:09:13	Watcher: version, status, reason = self._read_status()
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\httplib.py", line 448, in begin
info	Thu Feb 06 2020 15:09:13	Watcher: response.begin()
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\httplib.py", line 1148, in getresponse
info	Thu Feb 06 2020 15:09:13	Watcher: r = h.getresponse(buffering=True)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\urllib2.py", line 1201, in do_open
info	Thu Feb 06 2020 15:09:13	Watcher: return self.do_open(httplib.HTTPConnection, req)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\urllib2.py", line 1228, in http_open
info	Thu Feb 06 2020 15:09:13	Watcher: result = func(*args)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
info	Thu Feb 06 2020 15:09:13	Watcher: '_open', req)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\urllib2.py", line 447, in _open
info	Thu Feb 06 2020 15:09:13	Watcher: response = self._open(req, data)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\urllib2.py", line 429, in open
info	Thu Feb 06 2020 15:09:13	Watcher: return opener.open(url, data, timeout)
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\Python27\lib\urllib2.py", line 154, in urlopen
info	Thu Feb 06 2020 15:09:13	Watcher: response = json.loads(urlopen(request, timeout=600).read().decode('utf-8'))
info	Thu Feb 06 2020 15:09:13	Watcher: File "C:\ProgramData\NZBGet\scripts\Watcher.py", line 72, in <module>
info	Thu Feb 06 2020 15:09:13	Watcher: Traceback (most recent call last):
info	Thu Feb 06 2020 15:09:13	Watcher: Sending A.Beautiful.Day.in.the.Neighborhood.2019.2160p.UHD.BluRay.x265-TERMiNAL to Watcher as Complete.`

**Comment by barbequesauce** [comment]
Can you hit me up on IRC? I have QUESTIONS.

**Comment by barbequesauce** [comment]
So this is the NG plugin from barbequesauce/watcherplugins. Issue is a known timeout on the NG side when dealing with large files (10GB+) and moving between network locations.

Likely fix is to remove the actual move/copy from the plugin and simply issue the PP command; then let W3 do the work in a separate thread instead of having NG sit around waiting.

**Comment by barbequesauce** [comment]
Give that a spin...

**Comment by Obscurax** [comment]
Still happenings:

`
info | Sat Mar 13 2021 15:18:02 | Collection Raya.and.the.Last.Dragon.2021.2160p.DSNP.WEB-DL.DDP5.1.HDR.x265-NoGrp added to history
-- | -- | --
error | Sat Mar 13 2021 15:18:02 | Post-process-script  Watcher.py for  Raya.and.the.Last.Dragon.2021.2160p.DSNP.WEB-DL.DDP5.1.HDR.x265-NoGrp  failed (terminated with unknown status)
info | Sat Mar 13 2021 15:18:02 | Watcher: socket.timeout: timed out
info | Sat Mar 13 2021 15:18:02 | Watcher:     data = self._sock.recv(self._rbufsize)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\socket.py", line 480, in readline
info | Sat Mar 13 2021 15:18:02 | Watcher:     line = self.fp.readline(_MAXLINE + 1)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\httplib.py", line 404, in _read_status
info | Sat Mar 13 2021 15:18:02 | Watcher:     version, status, reason = self._read_status()
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\httplib.py", line 448, in begin
info | Sat Mar 13 2021 15:18:02 | Watcher:     response.begin()
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\httplib.py", line 1161, in getresponse
info | Sat Mar 13 2021 15:18:02 | Watcher:     r = h.getresponse(buffering=True)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\urllib2.py", line 1201, in do_open
info | Sat Mar 13 2021 15:18:02 | Watcher:     return self.do_open(httplib.HTTPConnection, req)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\urllib2.py", line 1228, in http_open
info | Sat Mar 13 2021 15:18:02 | Watcher:     result = func(*args)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
info | Sat Mar 13 2021 15:18:02 | Watcher:     '_open', req)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\urllib2.py", line 447, in _open
info | Sat Mar 13 2021 15:18:02 | Watcher:     response = self._open(req, data)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\urllib2.py", line 429, in open
info | Sat Mar 13 2021 15:18:02 | Watcher:     return opener.open(url, data, timeout)
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\Python27\lib\urllib2.py", line 154, in urlopen
info | Sat Mar 13 2021 15:18:02 | Watcher:     response = json.loads(urlopen(request, timeout=600).read().decode('utf-8'))
info | Sat Mar 13 2021 15:18:02 | Watcher:   File "C:\ProgramData\NZBGet\scripts\Watcher.py", line 72, in <module>
info | Sat Mar 13 2021 15:18:02 | Watcher: Traceback (most recent call last):
info | Sat Mar 13 2021 15:18:02 | Watcher: Sending Raya.and.the.Last.Dragon.2021.2160p.DSNP.WEB-DL.DDP5.1.HDR.x265-NoGrp to Watcher as Complete.
info | Sat Mar 13 2021 15:08:02 | Executing post-process-script Watcher.py for Raya.and.the.Last.Dragon.2021.2160p.DSNP.WEB-DL.DDP5.1.HDR.x265-NoGrp

`
