### ISSUE TITLE
nzbToWatcher3 with nzbget seems to fail on "failed nzb download" status

### ISSUE THREAD

**Issue by rafaello104** [barbequesauce/Watcher3#133]
**Describe the bug**
- I manually click a download option on my movie (this example: Rampage)
- nzb gets sent to my nzbget client (on same machine)
- nzb download fails, nzbget runs nzbToWatcher3
- nzbToWatcher3 reaches Watcher3 successfully
- A couple warnings happen and an error & the script terminates with unknown status
- The movie in Watcher3 still has status `snatched`

**To Reproduce**
1. Go to 'library -> specific movie'
2. Click on 'custom download and wait for the snatched nzb to fail'
3. Scroll down to 'cherrypy line in the logs'

**Expected behavior**
- I manually click a download option on my movie (this example: Rampage)
- nzb gets sent to my nzbget client (on same machine)
- nzb download fails, nzbget runs nzbToWatcher3
- nzbToWatcher3 reaches Watcher3 successfully
- the script runs successfully
- the movie gets status failed or bad or wanted and watcher keeps searching for a different release remembering the previous one is bad.

**Desktop:**
 - OS: `Windows 10 Pro build 1909`
 - Browser: `Chrome (latest)`
 - Version `Watcher latest version (fresh install)`
- Latest version of nzbToMedia

**Additional context**
I tried looking over the wiki, known issues and looked everywhere and couldn't find anyone with my issue and sadly I also didn't understand the log's error so this might be my fault in which case I am very sorry, I just seem to be stuck for over 3 days now and can't seem to solve this. If you need any more information please let me know I'll be watching this page closely.

**Log**
`````
INFO [2020-03-24 20:20:25,452] core.postprocessing.default.156: #################################
INFO [2020-03-24 20:20:25,453] core.postprocessing.default.157: Post-processing request received.
INFO [2020-03-24 20:20:25,453] core.postprocessing.default.158: #################################
INFO [2020-03-24 20:20:25,453] core.postprocessing.get_movie_file.247: Finding movie file.
WARNING [2020-03-24 20:20:25,453] core.postprocessing.get_movie_file.275: Unable to determine largest file. Postprocessing may fail at a later point.
WARNING [2020-03-24 20:20:25,453] core.postprocessing.default.186: Movie file not found
INFO [2020-03-24 20:20:25,453] core.postprocessing.default.190: Gathering release information.
INFO [2020-03-24 20:20:25,453] core.postprocessing.get_movie_info.303: Guid not found.
INFO [2020-03-24 20:20:25,453] core.postprocessing.get_movie_info.319: Searching local database for release name Rampage.2018.TrueHD.Atmos.AC3.MULTISUBS.1080p.BluRay.x264.1.HQ-TUSAHD-Obfuscated.#19956
INFO [2020-03-24 20:20:25,454] core.postprocessing.get_movie_info.324: Unable to find local release info by release name, trying fuzzy search.
INFO [2020-03-24 20:20:25,455] core.postprocessing.get_movie_info.329: Unable to find local release info by release name.
INFO [2020-03-24 20:20:25,455] core.postprocessing.get_movie_info.347: Unable to find local data for release. Using only data found from file.
WARNING [2020-03-24 20:20:25,455] core.postprocessing.default.195: Post-processing as Failed.
INFO [2020-03-24 20:20:25,455] core.postprocessing.failed.384: Marking guid as Bad.
ERROR [2020-03-24 20:20:25,455] cherrypy.error.2230425821320.error.219: [24/Mar/2020:20:20:25] HTTP 
Traceback (most recent call last):
  File "C:\Users\Admin\Watcher3\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\Admin\Watcher3\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Admin\Watcher3\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Users\Admin\Watcher3\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\Admin\Watcher3\core\postprocessing.py", line 196, in default
    response = self.failed(data)
  File "C:\Users\Admin\Watcher3\core\postprocessing.py", line 418, in failed
    if data['imdbid']:
KeyError: 'imdbid'
INFO [2020-03-24 20:20:25,458] cherrypy.error.2230425821320.error.219: [24/Mar/2020:20:20:25] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost:9090
  USER-AGENT: python-requests/2.21.0
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT: */*
  CONNECTION: keep-alive
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 178
`````

**Comment by rafaello104** [comment]
I am the greatest moron in the world, my apologies.
I wasn't using the new pp script that your project provides, rather the nzbtomedia one.

My apologies, swapped over from old repo where this wasn't the case, switched and it works like a charm. Good job my good sir!
