### ISSUE TITLE
Unable to add local Jackett torrents to remote Deluge (possibly other clients)

### ISSUE THREAD

**Issue by AtomiclyCursed** [barbequesauce/Watcher3#151]
**Describe the bug**
I have a Local/internal Jackett/Watcher3 setup with Remote Deluge but Watcher3 tries to add the torrent via URL which Deluge naturally doesn't have access too and produces the following error.
File "<string>", line 2, in raiseException
failure.raiseException()
File "/usr/local/lib/python2.7/dist-packages/deluge-1.3.15-py2.7.egg/deluge/core/rpcserver.py", line 317, in on_fail
lib.deluge_client.client.NoRouteError: Network is unreachable
raise exception(exception_msg)
File "/opt/watcher3/lib/deluge_client/client.py", line 226, in _receive_response
return self._receive_response(self.deluge_version, self.deluge_protocol_version)
File "/opt/watcher3/lib/deluge_client/client.py", line 247, in call
downloadid = (client.call('core.add_torrent_url', torrent['torrentfile'], options) or b'').decode('utf-8')
File "/opt/watcher3/core/downloaders/DelugeRPC.py", line 106, in add_torrent
Traceback (most recent call last):
ERROR [2020-04-27 00:20:39,066] core.downloaders.DelugeRPC.add_torrent.108: Unable to send torrent.

**To Reproduce**
Setup a local Jackett/Watcher3 (i use docker containers)
Add a remote Deluge Daemon or WebUI that doesn't have access to Jackett
Try send a torrent to deluge

**Expected behavior**
I would expect the torrent gets added correctly to Deluge and provides no error.

**Desktop (please complete the following information):**
 - linux
 - chrome 88
 - Watcher3 Latest (docker)
 - Jackett latest (docker)
 - Deluge 1.3.5

**Additional context**
This is a 50/50 bug/feature as it's broken but adding a feature would fix it.
possible option is change the usage of deluge.add_torrent_url to add_torrent_file downloading the torrent locally before doing this by default.
Or provide an option (tick-box, [ ] Send Torrent Binary) for an alternative path that does the above.
This is a problem for Both the Daemon and WebUI, solution is only for daemon but i think there would be a similar option for WebUI

**Comment by PrzemekSkw** [comment]
Hi @AtomiclyCursed can You tell me how to add Jackett to Watcher?
