### ISSUE TITLE
Movie Search Fails with "CPTaskScheduler._task.266: Scheduled Task Movie Search Failed:"

### ISSUE THREAD

**Issue by The1Magoo** [barbequesauce/Watcher3#158]
**Describe the bug**
Movies have stopped downloading a week or so ago.

**To Reproduce**
Scheduled Movie Search fails, and manually forcing a search reproduces the error.
No screen errors, but log shows :

WARNING [2020-05-29 19:30:16,062] CPTaskScheduler._task.266: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "/mnt/export/nas/Apps/watcher3/lib/cherrypyscheduler.py", line 264, in _task
    self.task()
  File "/mnt/export/nas/Apps/watcher3/core/searcher.py", line 86, in search_all
    search(imdbid, title, year, quality)
  File "/mnt/export/nas/Apps/watcher3/core/searcher.py", line 160, in search
    scored_results = searchresults.score(results, imdbid=imdbid)
  File "/mnt/export/nas/Apps/watcher3/core/searchresults.py", line 109, in score
    releases = score_year(releases, int(year))
ValueError: invalid literal for int() with base 10: 'N/A'
INFO [2020-05-29 19:30:16,130] CPTaskScheduler._task.273: == Finished Task: Movie Search ==

**Expected behavior**
Expect Movies to be found and downloaded :) (Was working previously, for a long time).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Failing on Server : Debian 9
 - Browser : CHrome, FIrefox

**Smartphone (please complete the following information):**
N/A

**Additional context**
I suspect the problem *MAY* have started when I deleted some older unwanted  movies through the Web interface, as the timing seems about right.

**Comment by The1Magoo** [comment]
Figured it out.. Movies with "N/A" as the release year cause this.. I had several, removing them stops the error..
