### ISSUE TITLE
Cannot launch Watcher

### ISSUE THREAD

**Issue by PrzemekSkw** [barbequesauce/Watcher3#185]
I try to launch Watcher on my Ubuntu 20.04 and have that issue:
```
lusia@lusia-laptop:~/Watcher3$ python3 watcher.py 
Creating database file /home/lusia/Watcher3/userdata/watcher.sqlite
Creating tables.
Connected to database sqlite:////home/lusia/Watcher3/userdata/watcher.sqlite
## Config file not found. Creating new basic config /home/lusia/Watcher3/userdata/config.cfg. Please review settings. 
Clearing Mako cache.
/home/lusia/Watcher3/core/searcher.py:72: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  backlog_movies = [i for i in movies if i['backlog'] != 1 and i['status'] is not 'Disabled' and Manage.verify(i, today=today)]
/home/lusia/Watcher3/lib/hachoir/parser/misc/pdf.py:395: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise ParserError("Can't find '%s' starting at %u"
/home/lusia/Watcher3/core/postprocessing.py:594: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.get('imdbid') and data['imdbid'] is not 'N/A':
Traceback (most recent call last):
  File "/home/lusia/Watcher3/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/home/lusia/Watcher3/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/home/lusia/Watcher3/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 140, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/home/lusia/Watcher3/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/home/lusia/Watcher3/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/home/lusia/Watcher3/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/home/lusia/Watcher3/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/home/lusia/Watcher3/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/home/lusia/Watcher3/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))
```

**Comment by barbequesauce** [comment]
What version of Python are you running? Watcher struggles with 3.8.x...

**Comment by PrzemekSkw** [comment]
@barbequesauce Hi, thanks for fast answer. I have python 3.8.5. Is there a way to fix that?

**Comment by barbequesauce** [comment]
It's been a project for several months now - many of our bundled dependencies are incompatible with 3.8 and need to be updated, and there are lots of issues with those updates. 

I'm hoping by Christmas...

**Comment by PrzemekSkw** [comment]
Can You tell me if I use Docker installation on my Ubuntu laptop, it will be OK?

**Comment by jandreaucodes** [comment]
I installed 3.7.9 to see if I could get Watcher to run again under that, but get the same error.

What's the newest version I can run Watcher3 on, running on macOS?

**Comment by eraldog** [comment]
Hello, I have the same errors on Python 3.8.5.
There is a way to let Watcher use other my other Python 2.7.10 in another path?
I'm on QNAP.

Thank you!

**Comment by barbequesauce** [comment]
Latest it will work on currently is 3.7x

**Comment by OneCDOnly** [comment]
@barbequesauce I'm hoping to get Watcher3 running again for QNAP users running Entware, but a recent package upgrade means we're now on Python 3.9.0. Will your updates work with Python 3.9.0 too?

**Comment by xoniq** [comment]
For future people, I came here because I updated to 20.04 LTS (Ubuntu) and encountered the same issue. To install `python3.7`:

1. Add PPA:
`sudo add-apt-repository ppa:deadsnakes/ppa`
2. Install `python3.7`:
  `sudo apt install python3.7`
3. Start Watcher:
  `python3.7 ~/Watcher3/watcher.py -p #### -d`

**Comment by PrzemekSkw** [comment]
@xoniq Thanks, now it works :)

**Comment by RicRock** [comment]
> For future people, I came here because I updated to 20.04 LTS (Ubuntu) and encountered the same issue. To install `python3.7`:
> 
> 1. Add PPA:
>    `sudo add-apt-repository ppa:deadsnakes/ppa`
> 2. Install `python3.7`:
>    `sudo apt install python3.7`
> 3. Start Watcher:
>    `python3.7 ~/Watcher3/watcher.py -p #### -d`

Exactly what I needed... Thanks!

**Comment by frustin** [comment]
came here looking for updates...my watcher3 app's not working anymore either.

**Comment by barbequesauce** [comment]
What version of python are you running? We're currently pinned to 3.7...

**Comment by frustin** [comment]
3.9, can’t get off it.

________________________________

**Comment by brendan-pike** [comment]
+1 from me, I can no longer run W3 either.  Please update to support 3.9!
