### ISSUE TITLE
Fault -501 and -506 for rTorrent 0.9.8

### ISSUE THREAD

**Issue by spyhuntergenral** [barbequesauce/Watcher3#195]
**Describe the bug**
Unable to send torrent to rTorrent HTTP

**To Reproduce**
Configured rTorrent Http downloader as below:

"rTorrentHTTP": {
"addpaused": true,  ###(true returns fault -506 and false returns -501)
"address": "http://RuTorrentIP/RPC2",
"enabled": true,
"label": "Watcher",
"pass": "",
"user": ""
},

**Expected behavior**
Torrent file gets added to rTorrent 

**Desktop (please complete the following information):**
 - OS: both watcher3 and rtorrent are running in dockers
 
Watcher3 Debug log:

 Fault -506: "Method 'load' not defined"
ERROR [2021-02-25 15:07:57,854] core.downloaders.rTorrentHTTP.add_torrent.92: Unable to send torrent to rTorrent HTTP
Traceback (most recent call last):
  File "/opt/watcher3/core/downloaders/rTorrentHTTP.py", line 74, in add_torrent
    client.load(data['torrentfile'])
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -506: "Method 'load' not defined">

Fault -501: 'Could not find info-hash.'
ERROR [2021-02-25 15:08:50,443] core.downloaders.rTorrentHTTP.add_torrent.92: Unable to send torrent to rTorrent HTTP
Traceback (most recent call last):
  File "/opt/watcher3/core/downloaders/rTorrentHTTP.py", line 76, in add_torrent
    client.load.start(data['torrentfile'])
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -501: 'Could not find info-hash.'>

Note: Current rTorrent is working fine with other applications i.e Sonarr, Sickrage

**Comment by barbequesauce** [comment]
What version of rTorrent, 0.9.8+?

**Comment by spyhuntergenral** [comment]
> 
> 
> What version of rTorrent, 0.9.8+?

Yip - rtorrent/libtorrent 0.9.8/0.13.8

**Comment by barbequesauce** [comment]
Does it work when you use the SCGI interface?

**Comment by AtomiclyCursed** [comment]
This is exactly the same as the error I reported at https://github.com/barbequesauce/Watcher3/issues/151 Problem in my case was Jackett hosted locally talking to a remote Deluge/rtorrent Client. 
The local Jackett url is sent but the torrent client can't connect to it due to the internal IP/URL which it can't access.

I was able to fix this by making Jackett public and accessible from the remote torrent client IP. 

To fix this issue watcher3 should download the torrent first (actually in all cases as this would be an issue for private torrent locations too as credentials are not sent along with it), then upload the file instead of passing a url. 
This will be a problem with all clients if they can't access the torrent's url.
