### ISSUE TITLE
traceback in log when running scheduled movie search

### ISSUE THREAD

**Issue by OneCDOnly** [barbequesauce/Watcher3#197]
Hi guys, I've noticed this today while looking over the logs. 

`environment:` I'm using Watcher3 pulled from GitHub source (master branch) on a Debian 10.8 server with Python 3.7.3. Also, after switching to the develop branch, I'm seeing the same error. 

`problem:` when Watcher3 runs the scheduled movie search, this error appears in my log.  

`debugging:` I've enabled debug logging and here's what appears just before the search task completes: 
```
...
DEBUG [2021-03-13 16:14:46,102] core.searchresults.score_sources.533: Removing Borderlands.Game.of.the.Year.Enhanced-PLAZA, size 18.01 not in range 500-20000.
INFO [2021-03-13 16:14:46,103] core.searchresults.score_sources.546: Keeping 7 releases.
WARNING [2021-03-13 16:14:46,103] CPTaskScheduler._task.266: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "/opt/Watcher3/lib/cherrypyscheduler.py", line 264, in _task
    self.task()
  File "/opt/Watcher3/core/searcher.py", line 77, in search_all
    search(movie)
  File "/opt/Watcher3/core/searcher.py", line 159, in search
    scored_results = searchresults.score(results, imdbid=imdbid)
  File "/opt/Watcher3/core/searchresults.py", line 116, in score
    releases = score_year(releases, int(year))
ValueError: invalid literal for int() with base 10: 'N/A'
DEBUG [2021-03-13 16:14:46,177] core.sqldb.row_exists.657: Checking if name="Movie Search" exists in database table TASKS
DEBUG [2021-03-13 16:14:46,177] core.sqldb.execute.168: Executing SQL command: ['SELECT 1 FROM TASKS WHERE name="Movie Search" COLLATE NOCASE']
DEBUG [2021-03-13 16:14:46,179] core.sqldb.update.252: Updating last_execution to 2021-03-13 16:14:30 for rows that match name:Movie Search in TASKS.
DEBUG [2021-03-13 16:14:46,180] core.sqldb.execute.168: Executing SQL command: ['UPDATE TASKS SET last_execution=? WHERE name=? COLLATE NOCASE', ('2021-03-13 16:14:30', 'Movie Search')]
INFO [2021-03-13 16:14:46,480] CPTaskScheduler._task.273: == Finished Task: Movie Search ==```
```
`question:` how can we fix this? 

Cheers!

**Comment by barbequesauce** [comment]
Agh the year bug again...

This one comes up when a metadata source has the year listed as anything other than a year, for example "TBD", "N/A", or null.

This specific bug was one of the reasons I forked in the first place, and obviously I still havent killed it...
