### ISSUE TITLE
Can't connect to transmission after upgrade

### ISSUE THREAD

**Issue by jamaroney** [barbequesauce/Watcher3#208]
After latest upgrades, I cannot connect to transmission. When I test it (on "Download Clients" page), I get the the following log error:

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
INFO [2023-02-12 06:02:03,810] core.downloaders.Transmission.test_connection.18: Testing connection to Transmission.
ERROR [2023-02-12 06:02:03,811] core.downloaders.Transmission.test_connection.35: Unable to connect to TransmissionRPC.
Traceback (most recent call last):
  File "/mnt/HDD/extensions/watcher/core/downloaders/Transmission.py", line 26, in test_connection
    client = transmission_rpc.Client(host, port, user=user, password=password)
TypeError: __init__() got an unexpected keyword argument 'user'
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

 - OS: FreeBSD 13.1

**Comment by barbequesauce** [comment]
Interesting. What version of transmission are you running?

**Comment by jamaroney** [comment]
version 3.0

**Comment by baudje** [comment]
same here, latest version Watcher, Transmission 3.00: 

> INFO [2023-05-10 09:29:14,342] cherrypy.error.84844496.error.213: [10/May/2023:09:29:14] HTTP
TypeError: Client.__init__() got an unexpected keyword argument 'user'
client = transmission_rpc.Client(host, port, user=user, password=password)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/core/downloaders/Transmission.py", line 59, in add_torrent
response = getattr(downloaders, client).add_torrent(data)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/core/snatcher.py", line 266, in snatch_torrent
response = snatch_torrent(data)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/core/snatcher.py", line 185, in download
return snatcher.download(data)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/core/ajax.py", line 290, in manual_download
return self.callable(*self.args, **self.kwargs)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/lib/cherrypy/_cpdispatch.py", line 54, in __call__
value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/lib/cherrypy/lib/jsontools.py", line 59, in json_handler
self.body = self.oldhandler(*args, **kwargs)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/lib/cherrypy/lib/encoding.py", line 223, in __call__
response.body = self.handler()
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/lib/cherrypy/_cprequest.py", line 697, in _do_respond
self._do_respond(path_info)
File "/share/CACHEDEV2_DATA/.qpkg/OWatcher3/repo-cache/lib/cherrypy/_cprequest.py", line 638, in respond
Traceback (most recent call last):
ERROR [2023-05-10 09:29:14,342] cherrypy.error.84844496.error.213: [10/May/2023:09:29:14] HTTP
INFO [2023-05-10 09:29:14,341] core.downloaders.Transmission.add_torrent.50: Sending torrent XXX to Transmission.
