### ISSUE TITLE
Failed import on Python3.7 on Windows system

### ISSUE THREAD

**Issue by sn3ak** [barbequesauce/Watcher3#213]
**Describe the bug**

```
C:\Watcher3>python watcher.py
Traceback (most recent call last):
  File "C:\Watcher3\lib\jaraco\text\__init__.py", line 7, in <module>
    from importlib.resources import files  # type: ignore
ImportError: cannot import name 'files' from 'importlib.resources' (C:\Program Files\Python37\lib\importlib\resources.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 10, in <module>
    import core         # noqa
  File "C:\Watcher3\core\__init__.py", line 4, in <module>
    import cherrypy
  File "C:\Watcher3\lib\cherrypy\__init__.py", line 66, in <module>
    from ._cperror import (
  File "C:\Watcher3\lib\cherrypy\_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "C:\Watcher3\lib\cherrypy\lib\httputil.py", line 20, in <module>
    import jaraco.collections
  File "C:\Watcher3\lib\jaraco\collections.py", line 10, in <module>
    import jaraco.text
  File "C:\Watcher3\lib\jaraco\text\__init__.py", line 9, in <module>
    from importlib_resources import files  # type: ignore
ModuleNotFoundError: No module named 'importlib_resources'
```

**To Reproduce**
1. Download Latest watcher3-master.zip from github
2. extract to C: and rename from watcher3-master to watcher3
3. Run python.exe watcher.py

**Expected behavior**
Watcher to start-up correctly

**Screenshots**
See output above

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Python: 3.7.9

**Comment by sn3ak** [comment]
Upgraded to python 3.11 and it works as expected
