### ISSUE TITLE
Error when searching with torrentz2

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#43]
I get this error for torrentz2 indexer:

ERROR [2019-10-02 20:00:03,823] core.providers.torrent_modules.torrentz2.search.29: Torrentz2 search failed.
Traceback (most recent call last):
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/watcher/lib/requests/adapters.py", line 436, in send
    timeout=timeout
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/app/watcher/lib/requests/packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/app/watcher/lib/requests/packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
lib.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.torrentz2.eu', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/watcher/core/providers/torrent_modules/torrentz2.py", line 20, in search
    response = Url.open(url).text
  File "/app/watcher/core/helpers.py", line 90, in open
    r = requests.get(url, **kwargs)
  File "/app/watcher/lib/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/app/watcher/lib/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/watcher/lib/requests/sessions.py", line 497, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/watcher/lib/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/app/watcher/lib/requests/adapters.py", line 512, in send
    raise ReadTimeout(e, request=request)
lib.requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.torrentz2.eu', port=443): Read timed out. (read timeout=30)

**Comment by barbequesauce** [comment]
This points to a client comes issue. What BT client are you using?

**Comment by scambra** [comment]
Transmission, but how is an issue in searchresults related to BT client? This error was raised when I clicked on search button.

Later, I saw torretnz2.eu raised a different error, XML not valid or something like that, so torrentz2.eu didn't time out, but watcher couldn't get results from torrentz2

**Comment by barbequesauce** [comment]
Sorry, was reading from a phone and understood the logs to say that it was having trouble sending the torrent to transmission. It's pretty clear that it's having trouble getting the torrent from torrentz2 though...  

Not sure what we can do about this except wrap it in a try/except loop?

**Comment by scambra** [comment]
Torrentz2 is working now, maybe it was some issue connecting to server
