### ISSUE TITLE
Connection to Transmission fails.

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#7]
Before submitting an issue...

* Enable debug logging in settings/server.

* Repeat the actions required to reproduce the error.

Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: 456731103ca682fc8fc199e0e9d2f52fd9a77f39
** Operating System: Mac OS 10.14.5
** Python Version [python -V]: 3.7.3
** What happened: When trying to add Transmission as a Downloader *and* a username & password is in place in Transmission, authentication fails. If I remove the authentication in Transmission, the connection is successful immediately.  This happens no matter what username and password combination I use.
** Logs:
If logs contain information you do not wish to share with the world you may email them to `watchernzb@gmail.com`. Include the issue number in the subject line of the message.
```
transmissionrpc.error.TransmissionError: Request failed. Original exception: HTTPHandlerError, "HTTPHandlerError 401: Unauthorized"
INFO [2019-07-31 04:40:46,773] core.ajax.save_settings.157: Saving settings.
INFO [2019-07-31 04:40:52,037] core.downloaders.Transmission.test_connection.17: Testing connection to Transmission.
ERROR [2019-07-31 04:40:52,045] core.downloaders.Transmission.test_connection.34: Unable to connect to TransmissionRPC.
Traceback (most recent call last):
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/httphandler.py", line 65, in request
    response = self.http_opener.open(request, timeout=timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 206, in _http_query
    result = self.http_handler.request(self.url, query, headers, timeout)
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/httphandler.py", line 72, in request
    raise HTTPHandlerError(error.filename, error.code, error.msg, dict(error.hdrs), error.read())
transmissionrpc.error.HTTPHandlerError: HTTPHandlerError 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Watcher/Watcher3/core/downloaders/Transmission.py", line 25, in test_connection
    client = transmissionrpc.Client(host, port, user=user, password=password)
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 170, in __init__
    self.get_session()
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 830, in get_session
    self._request('session-get', timeout=timeout)
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 248, in _request
    http_data = self._http_query(query, timeout)
  File "/Applications/Watcher/Watcher3/lib/transmissionrpc/client.py", line 224, in _http_query
    raise TransmissionError('Request failed.', error)
transmissionrpc.error.TransmissionError: Request failed. Original exception: HTTPHandlerError, "HTTPHandlerError 401: Unauthorized"
```

**Comment by jandreaucodes** [comment]
I _think_ I found the issue.

My username and password weren't being written to `/userdata/config.cfg`, even when I saved the settings.

I hardcoded them into the Transmission connection there, and the connection worked perfectly.

Other Config options are being written to the `config.cfg` file, so this looks like a bug specifically with the Downloader section.

**Comment by barbequesauce** [comment]
I can’t reproduce this. Can anyone else?
