### ISSUE TITLE
All flags except --userdata cause a traceback when config files do not exist

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#76]
**Describe the bug**
When no config files are present and watcher needs to create them, the majority of the flags result in an error and watcher fails to start.

**To Reproduce**
```
python3 watcher.py -c test.cfg -l test.log
```
Only the userdata flag seems to work:

`python3 watcher.py --userdata config-test`

Or Docker:

Pull barbequesauce/watcher3 and start with an empty config folder.

**Expected behavior**
The config files and database should be created if they do not exist.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 / Docker

**Additional context**
The problem does not occur if config files exist.

Example log from:

`python3 watcher.py -l log.log`

```Creating database file /home/ellnic/Desktop/Watcher3-master/userdata/watcher.sqlite
Creating tables.
Opening SQL DB.
Traceback (most recent call last):
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2141, in _wrap_pool_connect
    return fn()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ellnic/Desktop/Watcher3-master/core/sqldb.py", line 125, in __init__
    self.create_database(DB_NAME)
  File "/home/ellnic/Desktop/Watcher3-master/core/sqldb.py", line 144, in create_database
    self.metadata.create_all(self.engine)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/sql/schema.py", line 3848, in create_all
    tables=tables)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 1922, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 1915, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2106, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2145, in _wrap_pool_connect
    e, dialect, self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2141, in _wrap_pool_connect
    return fn()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
Traceback (most recent call last):
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2141, in _wrap_pool_connect
    return fn()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "watcher.py", line 84, in <module>
    core.sql = sqldb.SQL()
  File "/home/ellnic/Desktop/Watcher3-master/core/sqldb.py", line 125, in __init__
    self.create_database(DB_NAME)
  File "/home/ellnic/Desktop/Watcher3-master/core/sqldb.py", line 144, in create_database
    self.metadata.create_all(self.engine)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/sql/schema.py", line 3848, in create_all
    tables=tables)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 1922, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 1915, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2106, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2145, in _wrap_pool_connect
    e, dialect, self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/base.py", line 2141, in _wrap_pool_connect
    return fn()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ellnic/Desktop/Watcher3-master/lib/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file```

**Comment by scambra** [comment]
I have checked my docker based on linuxserver one, Docker file has this line:

COPY root/ /

And root has 2 files:
root/etc/cont-init.d/30-config
root/etc/services.d/watcher/run

30-config file creates empty directories in /config:
mkdir -p /config{/db,/logs,/plugins/added,/plugins/finished,/plugins/snatched,/scripts}

So I think watcher it may be failing to create /config/db directory:
```
$ python3 watcher.py -c test-config/watcher.cfg -l test-config/logs/ --db test-config/db/database.sqlite --plugins test-config/plugins/ --posters test-config/posters
Creating database file test-config/db/database.sqlite
Creating tables.
Opening SQL DB.
Traceback (most recent call last):

$ mkdir test-config
$ python3 watcher.py -c test-config/watcher.cfg -l test-config/logs/ --db test-config/db/database.sqlite --plugins test-config/plugins/ --posters test-config/posters
Creating database file test-config/db/database.sqlite
Creating tables.
Opening SQL DB.
Traceback (most recent call last):

$ mkdir test-config/db
$ python3 watcher.py -c test-config/watcher.cfg -l test-config/logs/ --db test-config/db/database.sqlite --plugins test-config/plugins/ --posters test-config/posters
Creating database file test-config/db/database.sqlite
Creating tables.
Connected to database sqlite:///test-config/db/database.sqlite
## Config file not found. Creating new basic config test-config/watcher.cfg. Please review settings. 
Clearing Mako cache.
```

**Comment by scambra** [comment]
Thanks @ellnic for pointing in the right direction

**Comment by scambra** [comment]
Starting without config directory now creates following structure:

```
ls -lR test-config/
test-config/:
total 24
drwxr-xr-x 2 osmc osmc  4096 Nov 22 09:39 db
drwxr-xr-x 2 osmc osmc  4096 Nov 22 09:39 logs
drwxr-xr-x 2 osmc osmc  4096 Nov 22 09:39 posters
-rw-r--r-- 1 osmc osmc 12202 Nov 22 09:39 watcher.cfg

test-config/db:
total 44
-rw-r--r-- 1 osmc osmc 40960 Nov 22 09:39 database.sqlite

test-config/logs:
total 4
-rw-r--r-- 1 osmc osmc 2036 Nov 22 09:39 log.txt

test-config/posters:
total 0
```

Using this command:
python3 watcher.py -c test-config/watcher.cfg -l test-config/logs/ --db test-config/db/database.sqlite --plugins test-config/plugins/ --posters test-config/posters

But it doesn't create plugins directory, it's probably right, because docker images can do it by themselves, so users have directory in userdata volume to drop plugins, but users running without docker can put plugins in watcher directory and don't use --plugins config param. Anyway, watcher is not failing, at least starting works.

I have tested a different command, with different directory for each arg:
python3 watcher.py -c test-config/watcher.cfg -l test-logs/ --db test-db/database.sqlite --plugins test-plugins/ --posters test-posters

It fails too, so I will add os.makedirs calls for other args too.

**Comment by ellnic** [comment]
Excellent. Thank you :)
