### ISSUE TITLE
Import from Couch Potato failing

### ISSUE THREAD

**Issue by jandreaucodes** [barbequesauce/Watcher3#8]
Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: 4567311
** Operating System: MacOS 10.14.5
** Python Version [python -V]: 3.7.3
** What happened: Trying to import from Couch Potato and I get an internal server error. It looks like it scans a bunch of my already downloaded movies, then errors out. It does not look to have scanned any of the Wanted list (which is what I wanted it to do)
** Logs: 
```
INFO [2019-07-31 04:59:13,671] core.library.get_movies.280: Reading CouchPotato library.
DEBUG [2019-07-31 04:59:14,722] core.sqldb.get_user_movies.327: Retrieving list of user's movies.
DEBUG [2019-07-31 04:59:14,722] core.sqldb.execute.156: Executing SQL command: ['SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC']
**THERE ARE A BUNCH OF OTHER MOVIES IT PARSES HERE, I CUT THEM FROM THE LOG BECAUSE THEY DON'T ADD ANYTHING HELPFUL**
DEBUG [2019-07-31 04:59:14,767] core.library.get_movies.303: Parsing CouchPotato movie Edward Scissorhands
ERROR [2019-07-31 04:59:14,768] cherrypy.error.4469918688.error.219: [31/Jul/2019:04:59:14] HTTP 
Traceback (most recent call last):
  File "/Applications/Watcher/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Applications/Watcher/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Watcher/Watcher3/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/Applications/Watcher/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Watcher/Watcher3/core/ajax.py", line 1057, in get_cp_movies
    return library.ImportCPLibrary.get_movies(url)
  File "/Applications/Watcher/Watcher3/core/library.py", line 360, in get_movies
    ts = cpm.get('release_date', {}).get('theater')
AttributeError: 'list' object has no attribute 'get'
INFO [2019-07-31 04:59:14,772] cherrypy.error.4469918688.error.219: [31/Jul/2019:04:59:14] HTTP 
Request Headers:
  Remote-Addr: 192.168.1.20
  HOST: 192.168.1.20:9090
  CONNECTION: keep-alive
  ACCEPT: */*
  ORIGIN: http://192.168.1.20:9090
  X-REQUESTED-WITH: XMLHttpRequest
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
  REFERER: http://192.168.1.20:9090/library/import/couchpotato
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: en-US,en;q=0.9,es;q=0.8
  COOKIE: movie_sort_key=release_date; session=92feb87dde2c197a75fe8f1a2e9ccec3cb982db4; movie_layout=posters; hide_finished_movies=True; movie_sort_direction=desc
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  Content-Length: 73
```

**Comment by jandreaucodes** [comment]
I managed to work around this, at least partially.

I first imported the directory where all of my downloaded movies are.
Only then did the sync from CouchPotato work and pull in all of the _wanted_ films.

**Comment by scambra** [comment]
I have imported from couchpotato with no error.
This issue may depend on data returned for movies in couchpotato, so it would be useful to have returned json from couchpotato, opening this URL in your browser:
http://IP:5050/api/API_KEY/movie.list/

**Comment by scambra** [comment]
@jandreaucodes can you provide json from couchpotato to debug this error

**Comment by jandreaucodes** [comment]
@scambra I don't have it anymore. I deleted CouchPotato at the first opportunity once I got Watcher3 installed.

I'd say go ahead and close this and if anyone else has issues, they can file a bug.
