### ISSUE TITLE
'null' error displayed when manually adding torrent to Deluge v2

### ISSUE THREAD

**Issue by ellnic** [barbequesauce/Watcher3#80]
**Describe the bug**
When clicking the download button on a torrent, a single 'null' is displayed in a red popup. This may be deluge related.

**To Reproduce**
1. Use deluge web UI option and Deluge v2.0.4 (possibly all v2)
2. Add movie
3. List search results
4. Click download button on a torrent result (it was a zooqle result if that makes any diff.)
5. See the red popup with 'null'

![null](https://user-images.githubusercontent.com/16370944/69493834-cbd2ae80-0eab-11ea-9dfe-c80135aae6d6.png)

Note: The torrent is, however, correctly sent to deluge. This appears to be more cosmetic.

**Expected behavior**
For the null error to not appear.

**Desktop:**
 - OS: Ubuntu 18.04 using Docker:

`Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
`
 - Browser: Firefox
 - Version: 70.0.1 (64-bit)

Note: Can also reproduce in Chromuium Version 78.0.3904.108 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Additional context**
This doesn't seem to affect operation. It's just cosmetic.

**Some Debug logs**

```INFO [2019-11-24 11:22:20,021] core.ajax.get_log_text.569: Dumping log file log.txt to text.
INFO [2019-11-24 11:22:17,289] core.ajax.get_log_text.569: Dumping log file log.txt.2019-11-19 to text.
lib.requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.17.0.9', port=8112): Read timed out. (read timeout=30)
raise ReadTimeout(e, request=request)
File "/opt/watcher3/lib/requests/adapters.py", line 512, in send
r = adapter.send(request, **kwargs)
File "/opt/watcher3/lib/requests/sessions.py", line 618, in send
resp = self.send(prep, **send_kwargs)
File "/opt/watcher3/lib/requests/sessions.py", line 497, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/watcher3/lib/requests/api.py", line 58, in request
return request('post', url, data=data, json=json, **kwargs)
File "/opt/watcher3/lib/requests/api.py", line 112, in post
r = requests.post(url, **kwargs)
File "/opt/watcher3/core/helpers.py", line 89, in open
response = Url.open(url, post_data=post_data, headers=headers)
File "/opt/watcher3/core/downloaders/DelugeWeb.py", line 104, in add_torrent
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

lib.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.17.0.9', port=8112): Read timed out. (read timeout=30)
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
File "/opt/watcher3/lib/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/opt/watcher3/lib/requests/packages/urllib3/connectionpool.py", line 388, in _make_request
chunked=chunked)
File "/opt/watcher3/lib/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
raise value
File "/opt/watcher3/lib/requests/packages/urllib3/packages/six.py", line 686, in reraise
raise six.reraise(type(error), error, _stacktrace)
File "/opt/watcher3/lib/requests/packages/urllib3/util/retry.py", line 347, in increment
_stacktrace=sys.exc_info()[2])
File "/opt/watcher3/lib/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
timeout=timeout
File "/opt/watcher3/lib/requests/adapters.py", line 436, in send
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

socket.timeout: timed out
return self._sock.recv_into(b)
File "/usr/lib/python3.6/socket.py", line 586, in readinto
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
version, status, reason = self._read_status()
File "/usr/lib/python3.6/http/client.py", line 307, in begin
response.begin()
File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
httplib_response = conn.getresponse()
File "/opt/watcher3/lib/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
File "<string>", line 2, in raise_from
six.raise_from(e, None)
File "/opt/watcher3/lib/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
Traceback (most recent call last):
ERROR [2019-11-24 11:19:31,763] core.downloaders.DelugeWeb.add_torrent.113: Delugeweb add_torrent
INFO [2019-11-24 11:19:08,874] core.downloaders.DelugeWeb.add_torrent.46: Sending torrent [Movie name redacted] to Deluge Web UI.
INFO [2019-11-24 11:19:08,874] core.snatcher.snatch_torrent.258: Sending magnet to DelugeWeb
INFO [2019-11-24 11:19:08,873] core.snatcher.download.164: Sending [Movie name redacted] to download client.
INFO [2019-11-24 11:19:01,740] core.downloaders.DelugeWeb.add_torrent.46: Sending torrent [Movie name redacted] to Deluge Web UI.
INFO [2019-11-24 11:19:01,740] core.snatcher.snatch_torrent.258: Sending magnet to DelugeWeb
INFO [2019-11-24 11:19:01,739] core.snatcher.download.164: Sending [Movie name redacted] to download client.```

**Comment by barbequesauce** [comment]
Not seeing it with transmission.

What version of deluge? v2 & v3 supposedly are quite different, wondering if that’s part of the problem.

Is this recently-new behavior?

**Comment by ellnic** [comment]
I don’t think deluge has reached v3 yet: https://dev.deluge-torrent.org/roadmap

I’m using the binhex/arch-delugevpn docker and I’ve just checked and it’s version 2.0.4dev20.

It’s not a recent thing, I just haven’t got round to submitting the issue.

**Comment by barbequesauce** [comment]
Eh sorry meant v2 - their api changed significantly from 1 to 2

**Comment by ellnic** [comment]
Np :) Deluge seems to have it's share of issues, but Transmission doesn't have everything I am looking for. Namely proxy settings, and I love the IP address display at the bottom.

**Comment by scambra** [comment]
is it torrent added to deluge? If it isn't, please rename this to support deluge api v2 or something like that

**Comment by ellnic** [comment]
The torrent is correctly added. I will correct the title to mention v2 though.

**Comment by scambra** [comment]
I will check with deluge daemon V2, I'm testing with 1.3 now

**Comment by ellnic** [comment]
Nice! Torrent correctly sent and label correctly applied. :+1:
